name: campuscrave
description: "No Q's, Only W's"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  flutter_native_splash: ^2.2.19 # Ensure this is in the dependencies section
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.6
  firebase_storage: ^11.6.7
  random_string: ^2.3.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  firebase_database: ^10.4.7
  provider: ^6.0.3
  get_storage : ^2.1.1
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0
  razorpay_flutter: 1.3.6
  google_sign_in : ^6.2.1 
  http: ^0.13.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: images/LoginIMG.png
  android: true
  ios: true

flutter:
  uses-material-design: true



  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
